---
title: "PM566 Final Project"
author: "Flemming Wu"
output:
  html_document:
    toc: true
    toc_float: true
---
This is my PM566 Final Project Website

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
```


```{r code chunk options}
# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px")
```


```{r load-data, echo=FALSE}
source("process_COVID_data.R")
```

```{r plots 1 and 2}
p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")


p3_hist <- cv_states %>%
  plot_ly(x = ~date, y = ~new_cases, color = ~state, alpha = 0.7, hoverinfo = "text", 
          text = ~paste(paste("Date:", date, sep = " "), paste("New Cases:", new_cases, sep = " "))) %>%
  add_bars() %>%
  layout(barmode = "overlay")
```

## Showcasing Plots {.tabset}

### Figure 1

```{r echo = FALSE}
p1_scatter
```

### Figure 2

```{r echo=FALSE}
p2_scatter
```

## {-}

## Other plots {.tabset}

### Figure 3

```{r echo=FALSE}
p3_hist
```

